### ISSUE TITLE
Error: FileReader is not defined

### ISSUE THREAD

**Issue by yannDroy** [abelalvarez89/xls-parser#3]
I keep getting this error, it's really not detailed enough in your readme...

```var xls_parser = require("xlsx-parse-json");```

```
var file = fs.readFileSync(filename);
xls_parser.onFileSelection(file)
.then((data) => {
    console.log(data);
});
```

OR

```
xls_parser.onFileSelection(filename)
.then((data) => {
    console.log(data);
});
```

Thank you :)

**Comment by abelalvarez89** [comment]
On the readme file I provide the usage of the library specifically, you can use the html file upload to get the file. Once you have uploaded the file then use that file and pass it into the function. I have an angular js example https://github.com/abelalvarez89/xls-parser/blob/master/example/src/index.js.

Also make sure you are importing or requiring `fs` https://code-maven.com/reading-a-file-with-nodejs

Assuming everything is in place the top snipped you provided should work. If you get stock don't hesitate in contacting me. Also provide a little more details as in what tech are you using and how are you uploading the file.
`
import xlsxParser from 'xlsx-parse-json';
var fs = require('fs');

function someFunction() {
   var file = fs.readFileSync('DATA', 'utf8');

   xlsxParser
     .onFileSelection(file)
     .then(data => {
       var parsedData = data;
     });
}
`
