### ISSUE TITLE
FileReader undefined

### ISSUE THREAD

**Issue by otatar** [abelalvarez89/xls-parser#5]
Where am I wrong?
(node:8012) UnhandledPromiseRejectionWarning: ReferenceError: FileReader is not defined

import xlsxParser from 'xls-parser'
import fs from 'fs'

function xlsx_parse(filename) {

    let data_file = fs.readFileSync(filename, 'utf8');

	xlsxParser
     .onFileSelection(filename)
     .then(data => {
       var parsedData = data;
       console.log(parsedData);
    });
}

xlsx_parse("podaci.xlsx");

**Comment by abelalvarez89** [comment]
the `xlsxParser.onFileSelection(file)` takes a file not a filename

**Comment by abelalvarez89** [comment]
Currently not supporting NodeJs, if you use a js framework it will work, `AngularJs`, `Angular`, `React`, `Vue`, etc
