### ISSUE TITLE
Excel Parser only finds string values

### ISSUE THREAD

**Issue by gbshhennsi** [abelalvarez89/xls-parser#6]
Hi! I like the Idea of your library and i am not finding a better one for my usecase :)

I am parsing the shown excel file 

![image](https://user-images.githubusercontent.com/53291773/120462728-7b3eea00-c39b-11eb-91b4-8e13b1df6625.png)

Do not wonder, i deleted the first sheet manually so its not visible inside the screenshot.

`const data = await xlsxParser.onFileSelection(blob);`

and what I get is an Object of this kind:

![image](https://user-images.githubusercontent.com/53291773/120462669-6e21fb00-c39b-11eb-9868-1c28e04f6564.png)

So it seems like the Library is only able to read strings out of my excel.
Is this somehow fixable to also detect numbers?

Thanks in advance!

**Comment by abelalvarez89** [comment]
Hello,  thanks for using the library.

I noticed few things. 
1) The first row should you be your header row
2) You can also try it directly on my website https://abelalvarez.info/xls-parser/
![image](https://user-images.githubusercontent.com/6484450/120478651-15426a80-c37b-11eb-9f2a-d461dfe34294.png)

![image](https://user-images.githubusercontent.com/6484450/120478459-df9d8180-c37a-11eb-893b-7e41f0d90397.png)

If that fails can you send a copy of your excel.

**Comment by gbshhennsi** [comment]
Thank you for your quick answer!!

So the excel file from the screenshot (without the titlepage) looks like this on your demo

![image](https://user-images.githubusercontent.com/53291773/120479903-c57d9680-c3ae-11eb-9981-403e29085d55.png)

It is not possible right now to add the topics to the first line but I think this shouldn't be a problem right now.

**Comment by gbshhennsi** [comment]
This is the excel file i am talking about
[2021-05-31_17-11-45_Excel_d.xlsx](https://github.com/abelalvarez89/xls-parser/files/6584532/2021-05-31_17-11-45_Excel_d.xlsx)

**Comment by abelalvarez89** [comment]
Just did a quick test removing your first row 
![image](https://user-images.githubusercontent.com/6484450/120481670-54be8600-c37e-11eb-8cb4-90495acd1db1.png)
![image](https://user-images.githubusercontent.com/6484450/120481699-5ee08480-c37e-11eb-9f2c-bbc4330cc8d2.png)

It seems to work correctly. The first row is required, that is the header row

**Comment by gbshhennsi** [comment]
Yep you are right, it also works for me like this.
Why is the first line an issue?
Is it because of the empty columns?

Also: shouldn't be the type of the "one" row be a number instead of string?

`"one" : string "17 °C"`

 Because °C is the unit and 17 is the number. 
You also see it inside the alignment of the excel

**Comment by abelalvarez89** [comment]
Im using the first line as my header line, then iterating though it to build the object you are getting. Since is empty is skipping.

one is a string `"17 °C"` because of the Celsius. Also I'm currently defaulting to take is as a string. If you need it as an number then you will need to change that column to be a number and you will need to make a small tweak in the library, doing so you may have an issue with dates. Let me know if you have any other question
